name: genezio-workflow
on:
  # Uncomment this to deploy your app for every push to main
  # push:
  #  branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: Genez-io/genezio-github-action@v1
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: deploy
        working-directory: ./
        run: genezio deploy --backend --stage prod
