name: genezio-workflow
on:
  # Uncomment this to deploy your app for every push to main
  # push:
  #  branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: Genez-io/genezio-github-action@v1
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Install Node.js dependencies
        working-directory: ./server
        run: npm ci
      - name: Install Node.js dependencies
        working-directory: ./client
        run: npm ci
      - name: deploy
        working-directory: ./
        run: genezio deploy --backend --stage prod
