name: genezio-workflow
on:
  push:
    branches:
      - main

jobs:
  deploy-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: Genez-io/genezio-github-action@main
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: deploy
        working-directory: ./
        run: genezio deploy —stage prod
